-- MySQL Script generated by MySQL Workbench
-- Fri Nov 12 23:12:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema el_mundo_del_calzado
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `el_mundo_del_calzado` ;

-- -----------------------------------------------------
-- Schema el_mundo_del_calzado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `el_mundo_del_calzado` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `el_mundo_del_calzado` ;

-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`categoria_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`categoria_usuario` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`categoria_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`colores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`colores` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`colores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`generos` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`generos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` CHAR(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`marcas` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`outlets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`outlets` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`outlets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TINYINT(2) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`talles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`talles` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`talles` (
  `id` INT NOT NULL,
  `nombre` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`, `nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`temporadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`temporadas` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`temporadas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TINYINT(2) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`productos` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` DECIMAL(6,2) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `id_generos` INT NOT NULL,
  `id_marcas` INT NOT NULL,
  `id_temporadas` INT NOT NULL,
  `id_outlets` INT NOT NULL,
  `id_talles` INT NOT NULL,
  `id_colores` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_generos_idx` (`id_generos` ASC) VISIBLE,
  INDEX `FK:_id_marcas_idx` (`id_marcas` ASC) VISIBLE,
  INDEX `FK_id_temporadas_idx` (`id_temporadas` ASC) VISIBLE,
  INDEX `FK_id_outlets_idx` (`id_outlets` ASC) VISIBLE,
  INDEX `FK_id_talles_idx` (`id_talles` ASC) VISIBLE,
  INDEX `FK_id_colores_idx` (`id_colores` ASC) VISIBLE,
  CONSTRAINT `FK_id_colores`
    FOREIGN KEY (`id_colores`)
    REFERENCES `el_mundo_del_calzado`.`colores` (`id`),
  CONSTRAINT `FK_id_generos`
    FOREIGN KEY (`id_generos`)
    REFERENCES `el_mundo_del_calzado`.`generos` (`id`),
  CONSTRAINT `FK_id_marcas`
    FOREIGN KEY (`id_marcas`)
    REFERENCES `el_mundo_del_calzado`.`marcas` (`id`),
  CONSTRAINT `FK_id_outlets`
    FOREIGN KEY (`id_outlets`)
    REFERENCES `el_mundo_del_calzado`.`outlets` (`id`),
  CONSTRAINT `FK_id_talles`
    FOREIGN KEY (`id_talles`)
    REFERENCES `el_mundo_del_calzado`.`talles` (`id`),
  CONSTRAINT `FK_id_temporadas`
    FOREIGN KEY (`id_temporadas`)
    REFERENCES `el_mundo_del_calzado`.`temporadas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`detalles` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `id_productos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_productos_idx` (`id_productos` ASC) VISIBLE,
  CONSTRAINT `FK_id_productos`
    FOREIGN KEY (`id_productos`)
    REFERENCES `el_mundo_del_calzado`.`productos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `id_categoria_usuario` INT NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_categoria_usuario_idx` (`id_categoria_usuario` ASC) VISIBLE,
  CONSTRAINT `FK_id_categoria_usuario`
    FOREIGN KEY (`id_categoria_usuario`)
    REFERENCES `el_mundo_del_calzado`.`categoria_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`orden` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_usuarios_idx` (`id_usuarios` ASC) VISIBLE,
  CONSTRAINT `FK_id_usuarios`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `el_mundo_del_calzado`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`carrito_de_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `el_mundo_del_calzado`.`carrito_de_compra` ;

CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`carrito_de_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NOT NULL,
  `id_productos` INT NOT NULL,
  `id_orden` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_usuarios_idx` (`id_usuarios` ASC) VISIBLE,
  INDEX `FK_id_productos_idx` (`id_productos` ASC) VISIBLE,
  INDEX `FK_id_orden_idx` (`id_orden` ASC) VISIBLE,
  CONSTRAINT `FK_id_usuarios`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `el_mundo_del_calzado`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_id_productos`
    FOREIGN KEY (`id_productos`)
    REFERENCES `el_mundo_del_calzado`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_id_orden`
    FOREIGN KEY (`id_orden`)
    REFERENCES `el_mundo_del_calzado`.`orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
