-- MySQL Script generated by MySQL Workbench
-- Sat Dec  4 01:09:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema el_mundo_del_calzado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema el_mundo_del_calzado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `el_mundo_del_calzado` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `el_mundo_del_calzado` ;

-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`generos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`temporadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`temporadas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`outlets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`outlets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `generoId` INT NULL DEFAULT NULL,
  `marcaId` INT NULL DEFAULT NULL,
  `temporadaId` INT NULL DEFAULT NULL,
  `outletId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `generoId` (`generoId` ASC) VISIBLE,
  INDEX `marcaId` (`marcaId` ASC) VISIBLE,
  INDEX `temporadaId` (`temporadaId` ASC) VISIBLE,
  INDEX `outletId` (`outletId` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`generoId`)
    REFERENCES `el_mundo_del_calzado`.`generos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`marcaId`)
    REFERENCES `el_mundo_del_calzado`.`marcas` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `productos_ibfk_3`
    FOREIGN KEY (`temporadaId`)
    REFERENCES `el_mundo_del_calzado`.`temporadas` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `productos_ibfk_4`
    FOREIGN KEY (`outletId`)
    REFERENCES `el_mundo_del_calzado`.`outlets` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 70
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`categoria_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`categoria_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `apellido` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `categoriaId` INT NULL DEFAULT NULL,
  `imagen` VARCHAR(100) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoriaId` (`categoriaId` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`categoriaId`)
    REFERENCES `el_mundo_del_calzado`.`categoria_usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`ordens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`ordens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarioId` INT NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuarioId` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `ordens_ibfk_1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `el_mundo_del_calzado`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`carrito_de_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`carrito_de_compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productoId` INT NULL DEFAULT NULL,
  `usuarioId` INT NULL DEFAULT NULL,
  `ordenId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productoId` (`productoId` ASC) VISIBLE,
  INDEX `usuarioId` (`usuarioId` ASC) VISIBLE,
  INDEX `ordenId` (`ordenId` ASC) VISIBLE,
  CONSTRAINT `carrito_de_compras_ibfk_1`
    FOREIGN KEY (`productoId`)
    REFERENCES `el_mundo_del_calzado`.`productos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `carrito_de_compras_ibfk_2`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `el_mundo_del_calzado`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `carrito_de_compras_ibfk_3`
    FOREIGN KEY (`ordenId`)
    REFERENCES `el_mundo_del_calzado`.`ordens` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`colores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `productoId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productoId` (`productoId` ASC) VISIBLE,
  CONSTRAINT `colores_ibfk_1`
    FOREIGN KEY (`productoId`)
    REFERENCES `el_mundo_del_calzado`.`productos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 193
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `productoId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productoId` (`productoId` ASC) VISIBLE,
  CONSTRAINT `detalles_ibfk_1`
    FOREIGN KEY (`productoId`)
    REFERENCES `el_mundo_del_calzado`.`productos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 270
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`imagenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `productoId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productoId` (`productoId` ASC) VISIBLE,
  CONSTRAINT `imagenes_ibfk_1`
    FOREIGN KEY (`productoId`)
    REFERENCES `el_mundo_del_calzado`.`productos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 312
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`sequelizemeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `el_mundo_del_calzado`.`talles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_mundo_del_calzado`.`talles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `productoId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productoId` (`productoId` ASC) VISIBLE,
  CONSTRAINT `talles_ibfk_1`
    FOREIGN KEY (`productoId`)
    REFERENCES `el_mundo_del_calzado`.`productos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 379
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
